translation:
  tra_dir: wildmage/tra

golem:
  mod_dir: wildmage
  platforms:
    - tob
    - bgee
    - bg2ee
    - bgt
    - sod
    - eet
  happy: true

mls:
  translation:
    directory: wildmage/tra/english
